### PR TITLE
fixes crash due to non-removal of files exceeding max, zeros out file…

### PR DESCRIPTION
**Pull request by zazula**
fixes crash due to non-removal of files exceeding max, zeros out file to allow tail -f to keep working.

### CODE REVIEW

**Comment by mczachurski** [comment]
Hi, Thank you for your PR. Unfortunately I cannot approve it. One of the requirement was to store in one log file some specific amount of data (e.g we shouldn't create files bigger than 10MB because it's hard to open them in editors). That's why there is a parameter `fileSizeLimitBytes`. Thanks to that parameter we know maximum amount of data which we can store in single file. When we achieve the limit we have to create a new file (the old one shouldn't be touched from that moment because we shouldn't remove any logged information) and new data should be logged into to new file.

I understand that `tail -f` will stop working when we achieve limit of data (data will be stored into new file). But we cannot overwrite logged data.

**Comment by zazula** [comment]
Hi -

OK, but the current behavior is to overwrite the file ifs size exceeds fileSizeLimitBytes.  This is due to the fact that getTimeStamp only appends a YYYYMM extension.  So, if I exceed the file size within the same day, I will close and re-open the same file, e.g., debug.202011.log.

Short of changing that behavior, please take the line:

	            self.filePath.removeAllCachedResourceValues()

in getFileSize() as it fixes a crasher related to the re-opening of the same file name — i.e., that the file size is never reset to 0 as getFileSize() returns a cached value.

Thanks,
Ralph

**Comment by mczachurski** [comment]
> the current behavior is to overwrite the file ifs size exceeds fileSizeLimitBytes.

This is real issue and it should be fixed. Maybe instead of your changes in `func saveToFile(data: Data)` you can `close` and `rename` old file in the function `func setNewFile()`. You can append to the file name some random string (https://stackoverflow.com/questions/26845307/generate-random-alphanumeric-string-in-swift). Then even if we will use again the same file name it will be new (empty) file. Probably removing cached values (`self.filePath.removeAllCachedResourceValues()`) is a good idea.

**Comment by zazula** [comment]
OK, I can take a stab at it.  My inclination is to expand the date format and use a sequence number in the case of collisions.  The question is, how long of a date format?

	YYYYMMDD.NNN.log (current + 3 digit sequence)

	YYYYMMDDhhmm.log (add hour+minute, sequence number on collision)
		202011120101.log
		202011120101.001.log
		…

	YYYYMMDDHHMMASS.log (H,M,S + sequence on collision (which should be rare)

Do you have a preference?

Thanks,
Ralph

**Comment by mczachurski** [comment]
Date format can be different and it's dependent of `rollingInterval` parameter (different prefix is for `.day` and different for `.hour` enum value). Thus I think we shouldn't change it, however additional sequence number is a very good idea.

**Comment by zazula** [comment]
Hi -

Please take a look:

	https://github.com/zazula/ExtendedLogging/commit/9f42ec24ec4613cb0bb30a71a5fdd091167374ab <https://github.com/zazula/ExtendedLogging/commit/9f42ec24ec4613cb0bb30a71a5fdd091167374ab>

It was a little more involved than I thought due to some tricky behavior with the async write queue.  I fixed a couple bugs related to that.

Note, I added a utility method to wait for the dispatch queue to empty for testing.  I wonder if this should be used on shutdown to let the final log entries go out?

Ralph

**Pull request merged**
